### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by kemfic** [uoip/pangolin#12]
I'm trying to compile for Python 3.7 on Windows with MinGW and cmake. When I run `cmake ..` I get the following error:
```-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Warning at python/CMakeLists.txt:3 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed. ```



How do I fix this?

**Comment by plasticuproject** [comment]
This project no longer seems to be maintained, and since it was only tested under Ubuntu 16.04, Python 3.6+, it looks like you're going to have to figure this one out.

**Comment by kemfic** [comment]
Oh, that's too bad. I'll post my solution if I can get it to work.

**Comment by plasticuproject** [comment]
That would be cool, as I have forked these bindings from the original C++ library, so if you're solution requires some code it would be nice to know.

**Comment by kemfic** [comment]
I've added a Findybind11.cmake file that's fixed that issue for now, but I haven't gotten it to compile yet. 

Now I'm getting issues with what seems to be a conflict with Git's sh.exe and CMake/MinGW. I can't remove or change shell to cmd, because pangolin requires git submodule to work for it to get its dependencies. 


I'll have to either clone and compile the dependencies separately, or use Visual Studio to compile it instead of CMake and MinGW. I'm gonna try that out tonight, and I'll keep y'all posted.

**Comment by Gatunox** [comment]
If you get it to work on Windows let m know, i've the same issue.

**Comment by kemfic** [comment]
I gave up on compiling this fork of pangolin on windows, unfortunately. It works fine on ubuntu. You can compile the original pangolin branch on windows pretty easily, though, and it comes with python bindings too.

**Comment by Gatunox** [comment]
How do I use the python binding form the original pangolin. I was able to
compile it as you mentioned. But I have no clue how to use it from python.
Like the other does. With the “import pangolin” sentence
Any ideas?  Thanks

**Comment by kemfic** [comment]
Read the Python Bindings section in the README. 
1. Run ```git submodule init && git submodule update```
2. Build pangolin
3. Add the directory of pangolin.so to your path, and import pangolin like so:


``` 
import sys
sys.path.append('path/to/so')
import pypangolin 
```

**Comment by voidless-03** [comment]
So I was able to compile the other pangolin on windows for python. Let me know if you want the binding :)

**Comment by Gatunox** [comment]
Hi,

Did you used it, I mean, Are you able to run it like the example shows?,
I've tried to compile it

Following these steps

git clone https://github.com/uoip/pangolin.git
cd pangolin
mkdir build
cd build
cmake ..
make -j8
cd ..
python setup.py install


But i have no clue of what't "make -j8" is supposed to make.
So i end up with the resulting build from "cmake ..", but i was not lucky
including that on the examples to make it work.

Can you give more detail of what you have done?

Thanks.

**Comment by Gatunox** [comment]
kemfic1 

how/where you found the Findybind11.cmake to include?

Thanks

**Comment by Gatunox** [comment]
FINALLY.

I was able to compile this and test it and it works. I had to edit some files configured by CMAKE manually because I am so NEW to cmake, but aflter almost 5 hours I was able to get it to work.

Many adjustments made to make it work. I wll try to make a summary later in case someone needs it.

Cya

**Comment by voidless-03** [comment]
Yea i adjusted 3 of the cmake files to make it work! Compared cmakes from the original pangolin as well.

**Comment by Haotian-Zhang** [comment]
> Yea i adjusted 3 of the cmake files to make it work! Compared cmakes from the original pangolin as well.

Hi @shuZro, 
Could you please share your modifications to compile the binding successfully? Appreciated!
