### ISSUE TITLE
C1083	Cannot open include file: 'pangolin/pangolin_export.h': No such file or director

### ISSUE THREAD

**Issue by voidless-03** [uoip/pangolin#15]
Cannot open include file: 'pangolin/pangolin_export.h': No such file or directory	_pangolin	C:\Users\Shuprio\Desktop\pangolin-master\include\pangolin\platform.h	45

**Comment by shuZro** [comment]
Has anyone tried this on window?

**Comment by nirajreginald1991** [comment]
@shuZro what was the solution?

**Comment by Hz2314** [comment]
I'm in the same problem. How do I solve it?
