### ISSUE TITLE
AttributeError: module 'pangolin' has no attribute 'CreateWindowAndBind'

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [uoip/pangolin#42]
I try to run the pangolin_hello_world file as specified in the readme and I get this error after building pangolin.

pangolin.CreateWindowAndBind('Main', 640, 480)
AttributeError: module 'pangolin' has no attribute 'CreateWindowAndBind'

**Comment by LINFF1023** [comment]
> I try to run the pangolin_hello_world file as specified in the readme and I get this error after building pangolin.
> 
> pangolin.CreateWindowAndBind('Main', 640, 480) AttributeError: module 'pangolin' has no attribute 'CreateWindowAndBind'

How to solve it ?
