### ISSUE TITLE
NameError: global name 'install_dirs' is not defined

### ISSUE THREAD

**Issue by kanishkaganguly** [uoip/pangolin#5]
When doing `python setup.py install` the script has referred to `install_dirs`  instead of `install_dir`.
A quick fix in the script is necessary.

**Comment by Richard-Owen-3DI** [comment]
Hello,

 I am keen to learn what solution was found for this, as I am encountering the same problem.

Regards

**Comment by plasticuproject** [comment]
Look at the pull requests, they have the fix, or clone from my fork.

**Comment by varun19299** [comment]
No the issue still exists. Could you send a pull request of the same?

I've manually corrected mine.

**Comment by Richard-Owen-3DI** [comment]
Can you confirm what this is in relation to?

**Comment by shubh2348** [comment]
NameError: global name 'saring_id_group0' is not defined how to fix it ? Plz help

**Comment by kanishkegb** [comment]
For anyone coming across this issue, as mention by @plasticuproject, simply renaming all `install_dirs` instances to `install_dir` in `setup.py` and running the command `python setup.py install` should work.
